name: Build

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

jobs:

  build:

    strategy:
      matrix:
        architecture: [win-x64, linux-x64]

    runs-on: windows-latest

    env:
      Solution_Name: Worker.sln

    steps:
    - uses: actions/checkout@v3
      with:
        repository: MillieSilva/RT-DeskLib
        ref: main
        ssh-key: ${{ secrets.DESKLIB_KEY }}
        path: Library

    - uses: actions/checkout@v3
      with:
        repository: MillieSilva/RT-Worker
        ref: main
        path: Worker

    - name: Install .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      working-directory: ./Worker
      run: dotnet restore

    - name: Build Publish
      working-directory: ./Worker
      run: dotnet publish -c Release -r ${{ matrix.architecture }} --self-contained true /p:UseAppHost=true

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.architecture }} Release
        path: .\Worker\bin\Release\net6.0\${{ matrix.architecture }}\publish

    - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: .\Worker\bin\Release\net6.0\${{ matrix.architecture }}\publish

