name: Build

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

jobs:

  build:

    strategy:
      matrix:
        architecture: [win-x64, linux-x64]

    runs-on: windows-latest

    env:
      Solution_Name: Worker.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build Publish
      run: dotnet publish -c Release -r ${{ matrix:architecture }} --self-contained true /p:UseAppHost=true

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.architecture }} Release
        path: bin/Release/net6.0/${{ matrix:architecture }}/publish/


